// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/sketchgate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`        // User or API key identifier
	Tokens        int64                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"` // Number of tokens to consume (default 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateRequest) Reset() {
	*x = CheckRateRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateRequest) ProtoMessage() {}

func (x *CheckRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateRequest.ProtoReflect.Descriptor instead.
func (*CheckRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRateRequest) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type CheckRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`                            // Remaining requests in window
	ResetAtMs     int64                  `protobuf:"varint,3,opt,name=reset_at_ms,json=resetAtMs,proto3" json:"reset_at_ms,omitempty"`         // When the window resets (unix ms)
	Penalized     bool                   `protobuf:"varint,4,opt,name=penalized,proto3" json:"penalized,omitempty"`                            // Whether user is in penalty queue
	PenaltyScore  float64                `protobuf:"fixed64,5,opt,name=penalty_score,json=penaltyScore,proto3" json:"penalty_score,omitempty"` // Current penalty score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateResponse) Reset() {
	*x = CheckRateResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateResponse) ProtoMessage() {}

func (x *CheckRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateResponse.ProtoReflect.Descriptor instead.
func (*CheckRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateResponse) GetResetAtMs() int64 {
	if x != nil {
		return x.ResetAtMs
	}
	return 0
}

func (x *CheckRateResponse) GetPenalized() bool {
	if x != nil {
		return x.Penalized
	}
	return false
}

func (x *CheckRateResponse) GetPenaltyScore() float64 {
	if x != nil {
		return x.PenaltyScore
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestCount      int64                  `protobuf:"varint,1,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"` // Current requests in window
	Limit             int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                   // Max requests allowed
	Remaining         int64                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetAtMs         int64                  `protobuf:"varint,4,opt,name=reset_at_ms,json=resetAtMs,proto3" json:"reset_at_ms,omitempty"`
	Penalized         bool                   `protobuf:"varint,5,opt,name=penalized,proto3" json:"penalized,omitempty"`
	PenaltyScore      float64                `protobuf:"fixed64,6,opt,name=penalty_score,json=penaltyScore,proto3" json:"penalty_score,omitempty"`
	FrequencyEstimate uint64                 `protobuf:"varint,7,opt,name=frequency_estimate,json=frequencyEstimate,proto3" json:"frequency_estimate,omitempty"`                                                      // CMS frequency estimate
	TierTokens        map[string]uint64      `protobuf:"bytes,8,rep,name=tier_tokens,json=tierTokens,proto3" json:"tier_tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Token bucket tier status
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *GetStatusResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStatusResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *GetStatusResponse) GetResetAtMs() int64 {
	if x != nil {
		return x.ResetAtMs
	}
	return 0
}

func (x *GetStatusResponse) GetPenalized() bool {
	if x != nil {
		return x.Penalized
	}
	return false
}

func (x *GetStatusResponse) GetPenaltyScore() float64 {
	if x != nil {
		return x.PenaltyScore
	}
	return 0
}

func (x *GetStatusResponse) GetFrequencyEstimate() uint64 {
	if x != nil {
		return x.FrequencyEstimate
	}
	return 0
}

func (x *GetStatusResponse) GetTierTokens() map[string]uint64 {
	if x != nil {
		return x.TierTokens
	}
	return nil
}

type GetPenaltyQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int64                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // Number of top offenders to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPenaltyQueueRequest) Reset() {
	*x = GetPenaltyQueueRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPenaltyQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPenaltyQueueRequest) ProtoMessage() {}

func (x *GetPenaltyQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPenaltyQueueRequest.ProtoReflect.Descriptor instead.
func (*GetPenaltyQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{4}
}

func (x *GetPenaltyQueueRequest) GetTopN() int64 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GetPenaltyQueueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entries        []*PenaltyEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalPenalized int64                  `protobuf:"varint,2,opt,name=total_penalized,json=totalPenalized,proto3" json:"total_penalized,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPenaltyQueueResponse) Reset() {
	*x = GetPenaltyQueueResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPenaltyQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPenaltyQueueResponse) ProtoMessage() {}

func (x *GetPenaltyQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPenaltyQueueResponse.ProtoReflect.Descriptor instead.
func (*GetPenaltyQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{5}
}

func (x *GetPenaltyQueueResponse) GetEntries() []*PenaltyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetPenaltyQueueResponse) GetTotalPenalized() int64 {
	if x != nil {
		return x.TotalPenalized
	}
	return 0
}

type PenaltyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Violations    float64                `protobuf:"fixed64,2,opt,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PenaltyEntry) Reset() {
	*x = PenaltyEntry{}
	mi := &file_proto_sketchgate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PenaltyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PenaltyEntry) ProtoMessage() {}

func (x *PenaltyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PenaltyEntry.ProtoReflect.Descriptor instead.
func (*PenaltyEntry) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{6}
}

func (x *PenaltyEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PenaltyEntry) GetViolations() float64 {
	if x != nil {
		return x.Violations
	}
	return 0
}

type PardonUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PardonUserRequest) Reset() {
	*x = PardonUserRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PardonUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PardonUserRequest) ProtoMessage() {}

func (x *PardonUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PardonUserRequest.ProtoReflect.Descriptor instead.
func (*PardonUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{7}
}

func (x *PardonUserRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PardonUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PardonUserResponse) Reset() {
	*x = PardonUserResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PardonUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PardonUserResponse) ProtoMessage() {}

func (x *PardonUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PardonUserResponse.ProtoReflect.Descriptor instead.
func (*PardonUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{8}
}

func (x *PardonUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EstimateFrequencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFrequencyRequest) Reset() {
	*x = EstimateFrequencyRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFrequencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFrequencyRequest) ProtoMessage() {}

func (x *EstimateFrequencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFrequencyRequest.ProtoReflect.Descriptor instead.
func (*EstimateFrequencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{9}
}

func (x *EstimateFrequencyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EstimateFrequencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      uint64                 `protobuf:"varint,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateFrequencyResponse) Reset() {
	*x = EstimateFrequencyResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateFrequencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateFrequencyResponse) ProtoMessage() {}

func (x *EstimateFrequencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateFrequencyResponse.ProtoReflect.Descriptor instead.
func (*EstimateFrequencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{10}
}

func (x *EstimateFrequencyResponse) GetEstimate() uint64 {
	if x != nil {
		return x.Estimate
	}
	return 0
}

func (x *EstimateFrequencyResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_sketchgate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RedisStatus   string                 `protobuf:"bytes,2,opt,name=redis_status,json=redisStatus,proto3" json:"redis_status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_sketchgate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sketchgate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_sketchgate_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetRedisStatus() string {
	if x != nil {
		return x.RedisStatus
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_sketchgate_proto protoreflect.FileDescriptor

const file_proto_sketchgate_proto_rawDesc = "" +
	"\n" +
	"\x16proto/sketchgate.proto\x12\n" +
	"sketchgate\"<\n" +
	"\x10CheckRateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x03R\x06tokens\"\xae\x01\n" +
	"\x11CheckRateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\x1e\n" +
	"\vreset_at_ms\x18\x03 \x01(\x03R\tresetAtMs\x12\x1c\n" +
	"\tpenalized\x18\x04 \x01(\bR\tpenalized\x12#\n" +
	"\rpenalty_score\x18\x05 \x01(\x01R\fpenaltyScore\"$\n" +
	"\x10GetStatusRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x8d\x03\n" +
	"\x11GetStatusResponse\x12#\n" +
	"\rrequest_count\x18\x01 \x01(\x03R\frequestCount\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\x12\x1e\n" +
	"\vreset_at_ms\x18\x04 \x01(\x03R\tresetAtMs\x12\x1c\n" +
	"\tpenalized\x18\x05 \x01(\bR\tpenalized\x12#\n" +
	"\rpenalty_score\x18\x06 \x01(\x01R\fpenaltyScore\x12-\n" +
	"\x12frequency_estimate\x18\a \x01(\x04R\x11frequencyEstimate\x12N\n" +
	"\vtier_tokens\x18\b \x03(\v2-.sketchgate.GetStatusResponse.TierTokensEntryR\n" +
	"tierTokens\x1a=\n" +
	"\x0fTierTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"-\n" +
	"\x16GetPenaltyQueueRequest\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x03R\x04topN\"v\n" +
	"\x17GetPenaltyQueueResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.sketchgate.PenaltyEntryR\aentries\x12'\n" +
	"\x0ftotal_penalized\x18\x02 \x01(\x03R\x0etotalPenalized\"@\n" +
	"\fPenaltyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x01(\x01R\n" +
	"violations\"%\n" +
	"\x11PardonUserRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\".\n" +
	"\x12PardonUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x18EstimateFrequencyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\x19EstimateFrequencyResponse\x12\x1a\n" +
	"\bestimate\x18\x01 \x01(\x04R\bestimate\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"\x0f\n" +
	"\rHealthRequest\"t\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fredis_status\x18\x02 \x01(\tR\vredisStatus\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds2\xed\x03\n" +
	"\vRateLimiter\x12H\n" +
	"\tCheckRate\x12\x1c.sketchgate.CheckRateRequest\x1a\x1d.sketchgate.CheckRateResponse\x12H\n" +
	"\tGetStatus\x12\x1c.sketchgate.GetStatusRequest\x1a\x1d.sketchgate.GetStatusResponse\x12Z\n" +
	"\x0fGetPenaltyQueue\x12\".sketchgate.GetPenaltyQueueRequest\x1a#.sketchgate.GetPenaltyQueueResponse\x12K\n" +
	"\n" +
	"PardonUser\x12\x1d.sketchgate.PardonUserRequest\x1a\x1e.sketchgate.PardonUserResponse\x12`\n" +
	"\x11EstimateFrequency\x12$.sketchgate.EstimateFrequencyRequest\x1a%.sketchgate.EstimateFrequencyResponse\x12?\n" +
	"\x06Health\x12\x19.sketchgate.HealthRequest\x1a\x1a.sketchgate.HealthResponseB)Z'github.com/kranthi0003/SketchGate/protob\x06proto3"

var (
	file_proto_sketchgate_proto_rawDescOnce sync.Once
	file_proto_sketchgate_proto_rawDescData []byte
)

func file_proto_sketchgate_proto_rawDescGZIP() []byte {
	file_proto_sketchgate_proto_rawDescOnce.Do(func() {
		file_proto_sketchgate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sketchgate_proto_rawDesc), len(file_proto_sketchgate_proto_rawDesc)))
	})
	return file_proto_sketchgate_proto_rawDescData
}

var file_proto_sketchgate_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_sketchgate_proto_goTypes = []any{
	(*CheckRateRequest)(nil),          // 0: sketchgate.CheckRateRequest
	(*CheckRateResponse)(nil),         // 1: sketchgate.CheckRateResponse
	(*GetStatusRequest)(nil),          // 2: sketchgate.GetStatusRequest
	(*GetStatusResponse)(nil),         // 3: sketchgate.GetStatusResponse
	(*GetPenaltyQueueRequest)(nil),    // 4: sketchgate.GetPenaltyQueueRequest
	(*GetPenaltyQueueResponse)(nil),   // 5: sketchgate.GetPenaltyQueueResponse
	(*PenaltyEntry)(nil),              // 6: sketchgate.PenaltyEntry
	(*PardonUserRequest)(nil),         // 7: sketchgate.PardonUserRequest
	(*PardonUserResponse)(nil),        // 8: sketchgate.PardonUserResponse
	(*EstimateFrequencyRequest)(nil),  // 9: sketchgate.EstimateFrequencyRequest
	(*EstimateFrequencyResponse)(nil), // 10: sketchgate.EstimateFrequencyResponse
	(*HealthRequest)(nil),             // 11: sketchgate.HealthRequest
	(*HealthResponse)(nil),            // 12: sketchgate.HealthResponse
	nil,                               // 13: sketchgate.GetStatusResponse.TierTokensEntry
}
var file_proto_sketchgate_proto_depIdxs = []int32{
	13, // 0: sketchgate.GetStatusResponse.tier_tokens:type_name -> sketchgate.GetStatusResponse.TierTokensEntry
	6,  // 1: sketchgate.GetPenaltyQueueResponse.entries:type_name -> sketchgate.PenaltyEntry
	0,  // 2: sketchgate.RateLimiter.CheckRate:input_type -> sketchgate.CheckRateRequest
	2,  // 3: sketchgate.RateLimiter.GetStatus:input_type -> sketchgate.GetStatusRequest
	4,  // 4: sketchgate.RateLimiter.GetPenaltyQueue:input_type -> sketchgate.GetPenaltyQueueRequest
	7,  // 5: sketchgate.RateLimiter.PardonUser:input_type -> sketchgate.PardonUserRequest
	9,  // 6: sketchgate.RateLimiter.EstimateFrequency:input_type -> sketchgate.EstimateFrequencyRequest
	11, // 7: sketchgate.RateLimiter.Health:input_type -> sketchgate.HealthRequest
	1,  // 8: sketchgate.RateLimiter.CheckRate:output_type -> sketchgate.CheckRateResponse
	3,  // 9: sketchgate.RateLimiter.GetStatus:output_type -> sketchgate.GetStatusResponse
	5,  // 10: sketchgate.RateLimiter.GetPenaltyQueue:output_type -> sketchgate.GetPenaltyQueueResponse
	8,  // 11: sketchgate.RateLimiter.PardonUser:output_type -> sketchgate.PardonUserResponse
	10, // 12: sketchgate.RateLimiter.EstimateFrequency:output_type -> sketchgate.EstimateFrequencyResponse
	12, // 13: sketchgate.RateLimiter.Health:output_type -> sketchgate.HealthResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_sketchgate_proto_init() }
func file_proto_sketchgate_proto_init() {
	if File_proto_sketchgate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sketchgate_proto_rawDesc), len(file_proto_sketchgate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sketchgate_proto_goTypes,
		DependencyIndexes: file_proto_sketchgate_proto_depIdxs,
		MessageInfos:      file_proto_sketchgate_proto_msgTypes,
	}.Build()
	File_proto_sketchgate_proto = out.File
	file_proto_sketchgate_proto_goTypes = nil
	file_proto_sketchgate_proto_depIdxs = nil
}
