// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/sketchgate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimiter_CheckRate_FullMethodName         = "/sketchgate.RateLimiter/CheckRate"
	RateLimiter_GetStatus_FullMethodName         = "/sketchgate.RateLimiter/GetStatus"
	RateLimiter_GetPenaltyQueue_FullMethodName   = "/sketchgate.RateLimiter/GetPenaltyQueue"
	RateLimiter_PardonUser_FullMethodName        = "/sketchgate.RateLimiter/PardonUser"
	RateLimiter_EstimateFrequency_FullMethodName = "/sketchgate.RateLimiter/EstimateFrequency"
	RateLimiter_Health_FullMethodName            = "/sketchgate.RateLimiter/Health"
)

// RateLimiterClient is the client API for RateLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SketchGate rate limiting service.
type RateLimiterClient interface {
	// Check if a request is allowed under rate limits.
	CheckRate(ctx context.Context, in *CheckRateRequest, opts ...grpc.CallOption) (*CheckRateResponse, error)
	// Get current rate limit status for a key.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Get the penalty queue (top offenders).
	GetPenaltyQueue(ctx context.Context, in *GetPenaltyQueueRequest, opts ...grpc.CallOption) (*GetPenaltyQueueResponse, error)
	// Pardon a user from the penalty queue.
	PardonUser(ctx context.Context, in *PardonUserRequest, opts ...grpc.CallOption) (*PardonUserResponse, error)
	// Get frequency estimate from Count-Min Sketch.
	EstimateFrequency(ctx context.Context, in *EstimateFrequencyRequest, opts ...grpc.CallOption) (*EstimateFrequencyResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type rateLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterClient(cc grpc.ClientConnInterface) RateLimiterClient {
	return &rateLimiterClient{cc}
}

func (c *rateLimiterClient) CheckRate(ctx context.Context, in *CheckRateRequest, opts ...grpc.CallOption) (*CheckRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRateResponse)
	err := c.cc.Invoke(ctx, RateLimiter_CheckRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RateLimiter_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) GetPenaltyQueue(ctx context.Context, in *GetPenaltyQueueRequest, opts ...grpc.CallOption) (*GetPenaltyQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPenaltyQueueResponse)
	err := c.cc.Invoke(ctx, RateLimiter_GetPenaltyQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) PardonUser(ctx context.Context, in *PardonUserRequest, opts ...grpc.CallOption) (*PardonUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PardonUserResponse)
	err := c.cc.Invoke(ctx, RateLimiter_PardonUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) EstimateFrequency(ctx context.Context, in *EstimateFrequencyRequest, opts ...grpc.CallOption) (*EstimateFrequencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateFrequencyResponse)
	err := c.cc.Invoke(ctx, RateLimiter_EstimateFrequency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RateLimiter_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimiterServer is the server API for RateLimiter service.
// All implementations must embed UnimplementedRateLimiterServer
// for forward compatibility.
//
// SketchGate rate limiting service.
type RateLimiterServer interface {
	// Check if a request is allowed under rate limits.
	CheckRate(context.Context, *CheckRateRequest) (*CheckRateResponse, error)
	// Get current rate limit status for a key.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Get the penalty queue (top offenders).
	GetPenaltyQueue(context.Context, *GetPenaltyQueueRequest) (*GetPenaltyQueueResponse, error)
	// Pardon a user from the penalty queue.
	PardonUser(context.Context, *PardonUserRequest) (*PardonUserResponse, error)
	// Get frequency estimate from Count-Min Sketch.
	EstimateFrequency(context.Context, *EstimateFrequencyRequest) (*EstimateFrequencyResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRateLimiterServer()
}

// UnimplementedRateLimiterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimiterServer struct{}

func (UnimplementedRateLimiterServer) CheckRate(context.Context, *CheckRateRequest) (*CheckRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRate not implemented")
}
func (UnimplementedRateLimiterServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRateLimiterServer) GetPenaltyQueue(context.Context, *GetPenaltyQueueRequest) (*GetPenaltyQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPenaltyQueue not implemented")
}
func (UnimplementedRateLimiterServer) PardonUser(context.Context, *PardonUserRequest) (*PardonUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PardonUser not implemented")
}
func (UnimplementedRateLimiterServer) EstimateFrequency(context.Context, *EstimateFrequencyRequest) (*EstimateFrequencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateFrequency not implemented")
}
func (UnimplementedRateLimiterServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRateLimiterServer) mustEmbedUnimplementedRateLimiterServer() {}
func (UnimplementedRateLimiterServer) testEmbeddedByValue()                     {}

// UnsafeRateLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServer will
// result in compilation errors.
type UnsafeRateLimiterServer interface {
	mustEmbedUnimplementedRateLimiterServer()
}

func RegisterRateLimiterServer(s grpc.ServiceRegistrar, srv RateLimiterServer) {
	// If the following call panics, it indicates UnimplementedRateLimiterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimiter_ServiceDesc, srv)
}

func _RateLimiter_CheckRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).CheckRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_CheckRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).CheckRate(ctx, req.(*CheckRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_GetPenaltyQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPenaltyQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).GetPenaltyQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_GetPenaltyQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).GetPenaltyQueue(ctx, req.(*GetPenaltyQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_PardonUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PardonUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).PardonUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_PardonUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).PardonUser(ctx, req.(*PardonUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_EstimateFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateFrequencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).EstimateFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_EstimateFrequency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).EstimateFrequency(ctx, req.(*EstimateFrequencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimiter_ServiceDesc is the grpc.ServiceDesc for RateLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sketchgate.RateLimiter",
	HandlerType: (*RateLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRate",
			Handler:    _RateLimiter_CheckRate_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RateLimiter_GetStatus_Handler,
		},
		{
			MethodName: "GetPenaltyQueue",
			Handler:    _RateLimiter_GetPenaltyQueue_Handler,
		},
		{
			MethodName: "PardonUser",
			Handler:    _RateLimiter_PardonUser_Handler,
		},
		{
			MethodName: "EstimateFrequency",
			Handler:    _RateLimiter_EstimateFrequency_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RateLimiter_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sketchgate.proto",
}
